package scoredAnnotation;

import annotation.Annotation;
import org.drools.ruleunits.api.DataSource;
import org.drools.ruleunits.api.DataStore;
import org.drools.ruleunits.api.RuleUnitData;

import java.util.Collection;

/**
 * Drools Rule Unit data for Stage 4.
 *
 * <p>The DataStore is the working memory for the rule unit. The application adds
 * empty ScoredAnnotation facts and Drools updates their scoreAdduct values.</p>
 *
 * <p>The matching DRL file is located at
 * {@code src/main/resources/scoredAnnotation/adduct-pattern-scoring.drl}. Its
 * {@code unit AdductPatternScoringUnit;} declaration binds those rules to this
 * Java class.</p>
 */
public class AdductPatternScoringUnit implements RuleUnitData {

    private final DataStore<ScoredAnnotation> scoredAnnotations;

    /**
     * Creates an empty rule-unit data object.
     *
     * <p>Facts can be added later through {@link #addScoredAnnotation} or
     * directly through {@link #getScoredAnnotations()}.</p>
     */
    public AdductPatternScoringUnit() {
        this.scoredAnnotations = DataSource.createStore();
    }

    /**
     * Creates a rule-unit data object and inserts the provided scored annotations
     * into its Drools working memory.
     *
     * @param scoredAnnotations facts to insert before firing the rules
     */
    public AdductPatternScoringUnit(Collection<ScoredAnnotation> scoredAnnotations) {
        this();
        addScoredAnnotations(scoredAnnotations);
    }

    /**
     * Convenience factory for the output of Stage 3.
     *
     * <p>Stage 3 returns plain {@link Annotation} objects. Stage 4 needs
     * {@link ScoredAnnotation} facts, so this method wraps every annotation and
     * inserts it into a new rule-unit data object.</p>
     *
     * @param annotations putative annotations generated by the database search
     * @return rule-unit data populated with empty scored annotations
     */
    public static AdductPatternScoringUnit fromAnnotations(Collection<Annotation> annotations) {
        AdductPatternScoringUnit unit = new AdductPatternScoringUnit();
        for (Annotation annotation : annotations) {
            unit.addScoredAnnotation(new ScoredAnnotation(annotation));
        }
        return unit;
    }

    /**
     * Returns the Drools data store containing {@link ScoredAnnotation} facts.
     *
     * <p>Drools rules access this property in DRL using the path
     * {@code /scoredAnnotations}.</p>
     *
     * @return working-memory data store for scored annotations
     */
    public DataStore<ScoredAnnotation> getScoredAnnotations() {
        return scoredAnnotations;
    }

    /**
     * Inserts one scored annotation into the rule-unit working memory.
     *
     * @param scoredAnnotation fact to insert
     */
    public void addScoredAnnotation(ScoredAnnotation scoredAnnotation) {
        scoredAnnotations.add(scoredAnnotation);
    }

    /**
     * Inserts several scored annotations into the rule-unit working memory.
     *
     * @param scoredAnnotations facts to insert
     */
    public void addScoredAnnotations(Collection<ScoredAnnotation> scoredAnnotations) {
        for (ScoredAnnotation scoredAnnotation : scoredAnnotations) {
            addScoredAnnotation(scoredAnnotation);
        }
    }

    /**
     * Computes the fuzzy compatibility between an observed adduct proportion and
     * the expected expert value.
     *
     * <p>The membership function follows the Stage 4 specification:</p>
     * <ul>
     *     <li>score {@code 1.0} when the deviation is at most {@code 0.2}</li>
     *     <li>linearly decreasing score between deviations {@code 0.2} and
     *     {@code 0.5}</li>
     *     <li>score {@code 0.0} when the deviation is greater than {@code 0.5}</li>
     * </ul>
     *
     * <p>For alanine, if the expected ratio is {@code 0.8}, observed ratios from
     * {@code 0.6} to {@code 1.0} score {@code 1.0}. Ratios such as {@code 0.4}
     * or {@code 1.1} receive partial scores.</p>
     *
     * @param observedProportion ratio measured from the feature intensities
     * @param expectedProportion expert expected ratio for this compound/adduct
     * @return fuzzy score between {@code 0.0} and {@code 1.0}
     */
    public static double fuzzyScore(double observedProportion, double expectedProportion) {
        if (Double.isNaN(observedProportion)) {
            return 0.0;
        }

        double deviation = Math.abs(observedProportion - expectedProportion);
        if (deviation <= 0.2) {
            return 1.0;
        }
        if (deviation > 0.5) {
            return 0.0;
        }

        return 1.0 - ((deviation - 0.2) / 0.3);
    }
}
