package scoredAnnotation;

import annotation.Annotation;
import org.drools.ruleunits.api.RuleUnitInstance;
import org.drools.ruleunits.api.RuleUnitProvider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Small facade for Stage 4 rule execution.
 *
 * <p>This class hides the Drools boilerplate from the rest of the application:
 * it creates the rule-unit data object, starts a {@link RuleUnitInstance}, fires
 * the rules, and closes the instance afterwards.</p>
 */
public class AdductPatternScoringService {

    /**
     * Wraps Stage 3 annotations as {@link ScoredAnnotation} facts and evaluates
     * their adduct-pattern scores with Drools.
     *
     * @param annotations putative compound annotations generated by Stage 3
     * @return scored annotation objects after the Stage 4 rules have fired
     */
    public List<ScoredAnnotation> scoreAdductPatterns(Collection<Annotation> annotations) {
        List<ScoredAnnotation> scoredAnnotations = new ArrayList<>();
        for (Annotation annotation : annotations) {
            scoredAnnotations.add(new ScoredAnnotation(annotation));
        }
        scoreAdductPatternsInPlace(scoredAnnotations);
        return scoredAnnotations;
    }

    /**
     * Runs the Stage 4 Drools rules on already-created scored annotations.
     *
     * <p>The objects in the provided collection are mutable facts. Drools updates
     * them in place by calling setters such as
     * {@link ScoredAnnotation#setScoreAdduct(Double)} from rule consequences.</p>
     *
     * @param scoredAnnotations scored annotation facts to insert into the rule
     *                          unit memory
     */
    public void scoreAdductPatternsInPlace(Collection<ScoredAnnotation> scoredAnnotations) {
        AdductPatternScoringUnit unitData = new AdductPatternScoringUnit(scoredAnnotations);
        try (RuleUnitInstance<AdductPatternScoringUnit> instance =
                     RuleUnitProvider.get().createRuleUnitInstance(unitData)) {
            instance.fire();
        }
    }
}
