package scoredAnnotation;

import annotation.Annotation;
import org.drools.ruleunits.api.RuleUnitInstance;
import org.drools.ruleunits.api.RuleUnitProvider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Small facade for Stage 5 retention-time rule execution.
 *
 * <p>This class hides the Drools boilerplate from the rest of the application:
 * it creates the rule-unit data object, starts a {@link RuleUnitInstance}, fires
 * the RT rules, and closes the instance afterwards.</p>
 */
public class RetentionTimeScoringService {

    /**
     * Wraps Stage 3 annotations as {@link ScoredAnnotation} facts and evaluates
     * their retention-time scores with Drools.
     *
     * @param annotations putative compound annotations generated by Stage 3
     * @return scored annotation objects after the Stage 5 rules have fired
     */
    public List<ScoredAnnotation> scoreRetentionTimes(Collection<Annotation> annotations) {
        List<ScoredAnnotation> scoredAnnotations = new ArrayList<>();
        for (Annotation annotation : annotations) {
            scoredAnnotations.add(new ScoredAnnotation(annotation));
        }
        scoreRetentionTimesInPlace(scoredAnnotations);
        return scoredAnnotations;
    }

    /**
     * Runs the Stage 5 Drools rules on already-created scored annotations.
     *
     * <p>The objects in the provided collection are mutable facts. Drools updates
     * them in place by calling {@link ScoredAnnotation#setScoreRT(Double)} from
     * rule consequences. Existing adduct scores are left untouched.</p>
     *
     * @param scoredAnnotations scored annotation facts to insert into the rule
     *                          unit memory
     */
    public void scoreRetentionTimesInPlace(Collection<ScoredAnnotation> scoredAnnotations) {
        RetentionTimeScoringUnit unitData = new RetentionTimeScoringUnit(scoredAnnotations);
        try (RuleUnitInstance<RetentionTimeScoringUnit> instance =
                     RuleUnitProvider.get().createRuleUnitInstance(unitData)) {
            instance.fire();
        }
    }
}