package scoredAnnotation;

import annotation.Annotation;
import org.drools.ruleunits.api.DataSource;
import org.drools.ruleunits.api.DataStore;
import org.drools.ruleunits.api.RuleUnitData;

import java.util.Collection;

/**
 * Drools Rule Unit data for Stage 5 retention-time scoring.
 *
 * <p>The RT rules compare each {@link ScoredAnnotation} fact against all other
 * annotations from different features. If the compound with the higher logP also
 * has the higher retention time, both annotations receive one positive RT
 * evidence count. If the higher logP compound elutes earlier, both annotations
 * receive one negative RT evidence count.</p>
 *
 * <p>Each {@link ScoredAnnotation} converts those counts into a score with the
 * formula {@code positive / (positive + negative)}.</p>
 *
 * <p>The matching DRL file is located at
 * {@code src/main/resources/scoredAnnotation/retention-time-scoring.drl}. Its
 * {@code unit RetentionTimeScoringUnit;} declaration binds those rules to this
 * Java class.</p>
 */
public class RetentionTimeScoringUnit implements RuleUnitData {

    private final DataStore<ScoredAnnotation> scoredAnnotations;

    /**
     * Creates an empty rule-unit data object.
     */
    public RetentionTimeScoringUnit() {
        this.scoredAnnotations = DataSource.createStore();
    }

    /**
     * Creates a rule-unit data object and inserts the provided scored
     * annotations into its Drools working memory.
     *
     * @param scoredAnnotations facts to insert before firing the rules
     */
    public RetentionTimeScoringUnit(Collection<ScoredAnnotation> scoredAnnotations) {
        this();
        addScoredAnnotations(scoredAnnotations);
    }

    /**
     * Convenience factory for Stage 3 annotations.
     *
     * @param annotations putative annotations generated by the database search
     * @return rule-unit data populated with empty scored annotations
     */
    public static RetentionTimeScoringUnit fromAnnotations(Collection<Annotation> annotations) {
        RetentionTimeScoringUnit unit = new RetentionTimeScoringUnit();
        for (Annotation annotation : annotations) {
            unit.addScoredAnnotation(new ScoredAnnotation(annotation));
        }
        return unit;
    }

    /**
     * Returns the Drools data store containing {@link ScoredAnnotation} facts.
     *
     * <p>Drools rules access this property in DRL using the path
     * {@code /scoredAnnotations}.</p>
     *
     * @return working-memory data store for scored annotations
     */
    public DataStore<ScoredAnnotation> getScoredAnnotations() {
        return scoredAnnotations;
    }

    /**
     * Inserts one scored annotation into the rule-unit working memory.
     *
     * @param scoredAnnotation fact to insert
     */
    public void addScoredAnnotation(ScoredAnnotation scoredAnnotation) {
        scoredAnnotations.add(scoredAnnotation);
    }

    /**
     * Inserts several scored annotations into the rule-unit working memory.
     *
     * @param scoredAnnotations facts to insert
     */
    public void addScoredAnnotations(Collection<ScoredAnnotation> scoredAnnotations) {
        for (ScoredAnnotation scoredAnnotation : scoredAnnotations) {
            addScoredAnnotation(scoredAnnotation);
        }
    }
}